

import 'dart:async';
import 'dart:ffi';
import 'dart:io';

String ?SelectedGender;
String ?SelectedLocation;
String ?SelectedMtachMakerExperience;
String ?SelectedDate;
DateTime? startdate;
String? datestring;
 File ?imgFile;
 String?Matchtype;
 String?match_with_id;
 String?match_from_id;
 String?match_type;
 String?Requeststatus;
 String? Ocupasion;
String verification_method="nationality_identity_card";
String?nationality;
File? ImagetoUpload;

String?Subcriptiontype;
  bool isSpinTimerVisible = false;
String?choose;
String ?listAsString;
String ?roomid;
String ?otpVerification;
  List<File> galleryImageFiles = [];
List <String>  interests=[];
  String? selectGender;
  String? selectchildren;
  String? selectEducation;
  String? selectHopping;

  String? selectSmoke;
  String? selectDrink;
    bool isVisible = true;
  bool isNotVisible = false;
int rolevalue=1;
File? videoFile;
 int ? selectedseekerid;
  String? selectExperience;
String ?match_fromid;
String ?requestId;
String ?match_withid;
String?chatimage;
String?chatname;
String?chatimage1;
String?chatname1;
String ?Makerid;
String ?Sikeraddress;
String? BioTitle;
String? BioDescription;
String? IntrestedIn;
String? Interests;
String ?SikerReligon;
String selectedCountry = '';
String? userIdsiker;
String? requestIdsiker;
String? requestid;
String requestype="1";
String?action_with;
String?action_from;
String?actiontype;
Bool ?liverpullrequested;
Bool ?spinnwillrequested;
  DateTime? startTime;
  DateTime? endTime;
int selectedRadioTile=0;
String messagetype="text";
String ?messageimgurl;
String ?messagaudiourl;
String ? anotherchatuser;
String ? makerchatuser;
String? Makeridchat;
String? name1;
String? name2;
String? img1;
String? im2;
List images = [];
String? myId;

bool islivierpooled=false;
bool isspinedwill=false;
String? myid;
bool ?makeride;